server:
  port: 8011

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  application:
    name: photo


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: FULL


############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: -1
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  #一人只生成一token
  maxTryTimes: -1
  #彩色日记
  isColorLog: true
  #是否尝试从 请求体 里读取 Token
  isReadBody: false
  #是否尝试从 cookie 里读取 Token，此值为 false 后，StpUtil.login(id) 登录时也不会再往前端注入Cookie
  isReadCookie: false
  #是否在登录后将 Token 写入到响应头
  isWriteHeader: false


#模型配置
modelset:

  #重要的事情说3遍！！！
  #两者不同搭配的效果和速度都不一样，如果你不知道这是干嘛的，请不要动
  #两者不同搭配的效果和速度都不一样，如果你不知道这是干嘛的，请不要动
  #两者不同搭配的效果和速度都不一样，如果你不知道这是干嘛的，请不要动


  #人像分割模型 - 可选值：modnet_photographic_portrait_matting | hivision_modnet | rmbg-1.4 | birefnet-v1-lite
  humanMattingModel: hivision_modnet
  #人脸检测模型 - 可选值：mtcnn | retinaface-resnet50
  faceDetectModel: mtcnn
